spinnaker:
  s3:
    enabled: true
    endpoint: http://minio:9000
    bucket: spinnaker
    region: us-east-1
    accessKeyId: minioadmin
    secretAccessKey: minioadmin
    pathStyleAccess: true
    versioning: false
