spinnaker:
  s3:
    enabled: true
    endpoint: http://127.0.0.1:9090
    region: us-east-1
    pathStyleAccess: true
    versioning: false

  spinnaker:
    extensibility:
      plugins-root-path: /opt/clouddriver/plugins
      plugins:
        Armory.ObservabilityPlugin:
          enabled: false
      repositories:
        armory-observability-plugin-releases:
          enabled: false

redis:
  enabled: false
  connection: redis://spin-redis:6379

sql:
  enabled: true
  connectionPools:
    jdbc:
      default:
        default: true
        jdbcUrl: jdbc:mariadb://spin-mariadb:3306/clouddriver
        user: spinnaker
        password: spinnaker
        driver: org.mariadb.jdbc.Driver
    tasks:
      default:
        jdbcUrl: jdbc:mariadb://spin-mariadb:3306/clouddriver
        user: spinnaker
        password: spinnaker
        driver: org.mariadb.jdbc.Driver
  migration:
    jdbcUrl: jdbc:mariadb://spin-mariadb:3306/clouddriver
    user: spinnaker
    password: spinnaker
