spinnaker:
  s3:
    enabled: true
    endpoint: http://127.0.0.1:9090
    region: us-east-1
    pathStyleAccess: true
    versioning: false

sql:
  enabled: true
  connectionPools:
    jdbc:
      default:
        default: true
        jdbcUrl: jdbc:mysql://spin-mariadb:3306/clouddriver
        user: spinnaker
        password: spinnaker
        driver: com.mysql.cj.jdbc.Driver
    tasks:
      default:
        jdbcUrl: jdbc:mysql://spin-mariadb:3306/clouddriver
        user: spinnaker
        password: spinnaker
        driver: com.mysql.cj.jdbc.Driver
  migration:
    jdbcUrl: jdbc:mysql://spin-mariadb:3306/clouddriver
    user: spinnaker
    password: spinnaker
