sql:
  enabled: true
  connectionPools:
    jdbc:
      default:
        default: true
        jdbcUrl: jdbc:mariadb://spin-mariadb:3306/echo
        user: spinnaker
        password: spinnaker
        driver: org.mariadb.jdbc.Driver
  migration:
    jdbcUrl: jdbc:mariadb://spin-mariadb:3306/echo
    user: spinnaker
    password: spinnaker
