sql:
  enabled: true
  connectionPools:
    jdbc:
      default:
        default: true
        jdbcUrl: jdbc:mysql://127.0.0.1:3306/igor
        user: spinnaker
        password: spinnaker
        driver: com.mysql.cj.jdbc.Driver
  migration:
    jdbcUrl: jdbc:mysql://127.0.0.1:3306/igor
    user: spinnaker
    password: spinnaker
