sql:
  enabled: true
  connectionPools:
    jdbc:
      default:
        default: true
        jdbcUrl: jdbc:mariadb://spin-mariadb:3306/orca
        user: spinnaker
        password: spinnaker
        driver: org.mariadb.jdbc.Driver
  migration:
    jdbcUrl: jdbc:mariadb://spin-mariadb:3306/orca
    user: spinnaker
    password: spinnaker

executionRepository:
  sql:
    enabled: true
  redis:
    enabled: false
