---
- name: Install nginx
  ansible.builtin.apt:
    name: nginx
    state: latest

- name: Remove default nginx config
  ansible.builtin.file:
    name: /etc/nginx/sites-enabled/default
    state: absent
  notify: restart nginx

- name: Create nginx server config
  ansible.builtin.copy:
    src: ../files/nginx.conf
    dest: /etc/nginx/nginx.conf
    mode: 0600
  notify: restart nginx

- name: Create nginx server config
  ansible.builtin.copy:
    src: ../files/nginx.conf
    dest: /etc/nginx/nginx.conf
    mode: 0600
  notify: restart nginx

- name: Create Spinnaker config for nginx
  ansible.builtin.template:
    src: ../files/spinnaker_nginx
    dest: /etc/nginx/sites-enabled/spinnaker
    mode: 0600
  notify: restart nginx