---
- name: Download spinnaker-community GPG key
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      curl -fsSL https://us-apt.pkg.dev/doc/repo-signing-key.gpg | \
        gpg --dearmor --yes -o /usr/share/keyrings/spinnaker-community.gpg
    creates: /usr/share/keyrings/spinnaker-community.gpg

- name: Add spinnaker-community apt repository
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/usr/share/keyrings/spinnaker-community.gpg arch=all] https://us-apt.pkg.dev/projects/spinnaker-community apt main
    state: present
    filename: spinnaker

- name: Install Java
  ansible.builtin.apt:
    name: openjdk-17-jre-headless
    state: present

- name: Install Halyard
  ansible.builtin.apt:
    name: "spinnaker-halyard"
    state: latest

- name: Wait for Halyard service to start
  ansible.builtin.pause:
    seconds: 15
