---
- hosts: all
  become: true

  tasks:
    - name: Include task to install packages that enable apt over HTTPS
      ansible.builtin.include_tasks: includes/apt_over_https.yml

    - name: Include task to install useful packages
      ansible.builtin.include_tasks: includes/install_useful_packages.yml

    - name: Include task to install docker
      ansible.builtin.include_tasks: includes/install_docker.yml

    - name: Download Jenkins apt key
      ansible.builtin.get_url:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
        dest: /tmp/jenkins.key
        mode: "0644"

    - name: Dearmor Jenkins apt key
      ansible.builtin.command:
        cmd: gpg --dearmor --yes -o /usr/share/keyrings/jenkins.gpg /tmp/jenkins.key
        creates: /usr/share/keyrings/jenkins.gpg

    - name: Set Jenkins apt repository
      ansible.builtin.apt_repository:
        repo: deb [signed-by=/usr/share/keyrings/jenkins.gpg] https://pkg.jenkins.io/debian-stable/ binary/
        filename: jenkins
        state: present

    - name: Install Java and Jenkins
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      loop:
        - openjdk-17-jre-headless
        - jenkins

    - name: Start Jenkins
      ansible.builtin.service:
        name: jenkins
        state: started
        enabled: yes

    - name: Get Admin password
      ansible.builtin.slurp:
        src: /var/lib/jenkins/secrets/initialAdminPassword
      register: admin_password

    - name: Print Admin password
      ansible.builtin.debug:
        msg: "{{ admin_password.content | b64decode | trim }}"

  # Setup a handler for restarting Docker daemon
  handlers:
    - name: restart docker
      ansible.builtin.service:
        name: docker
        state: restarted
